### ISSUE TITLE
release环境下一启动就crash

### ISSUE THREAD

**Issue by hllGitHub** [ValiantCat/XXShield#10]
<img width="858" alt="crash" src="https://user-images.githubusercontent.com/15081858/38928109-60faf678-433a-11e8-92ac-d0fba63925fc.png">
<img width="464" alt="crash" src="https://user-images.githubusercontent.com/15081858/38928112-613f7406-433a-11e8-9004-273de8169c9d.png">

debug的情况下可以

**Comment by hllGitHub** [comment]
这是在bugly下统计到的信息。App中是这样使用的。请问是跟哪里的配置冲突还是什么情况？
#ifdef DEBUG
#else
    // 设置防crash
    [self setupXXField];
#endif


#pragma mark - XXField
// 启动防crash设置
- (void)setupXXField {
//    [XXShieldSDK registerStabilitySDK];
    [XXShieldSDK registerStabilityWithAbility:EXXShieldTypeTimer];
    [XXShieldSDK registerStabilityWithAbility:EXXShieldTypeNSNull];
    [XXShieldSDK registerStabilityWithAbility:EXXShieldTypeContainer];
    [XXShieldSDK registerStabilityWithAbility:EXXShieldTypeNotification];
    [XXShieldSDK registerStabilityWithAbility:EXXShieldTypeUnrecognizedSelector];
    // KVO部分和YYText部分发生了冲突
//    [XXShieldSDK registerStabilityWithAbility:EXXShieldTypeKVO];
}

**Comment by jqoo** [comment]
`    struct dl_info self_info = {0};
    dladdr((__bridge void *)[self class], &self_info);
    
    //    ignore system class
    if (self_info.dli_fname == NULL || strcmp(app_info.dli_fname, self_info.dli_fname)) {
        return XXHookOrgin(aSelector);
    }
`
这样就可以了，self_info有可能获取不到

**Comment by ValiantCat** [comment]
please open a Pull Request to merge to solve this problem

**Comment by ValiantCat** [comment]
#15

**Comment by hllGitHub** [comment]
请问cocoapods什么时候会更新呢？

**Comment by ValiantCat** [comment]
现在就发

**Comment by ValiantCat** [comment]
2.2.0 已经发布

**Comment by hllGitHub** [comment]
非常感谢！
