### ISSUE TITLE
程序启动闪退 (NSArrayObjectAtIndex.h:17)

### ISSUE THREAD

**Issue by faterman** [ValiantCat/XXShield#12]
Fatal Exception: NSInvalidArgumentException
*** -[NSArray objectAtIndex:]: method only defined for abstract class. Define -[__NSSingleObjectArrayI objectAtIndex:]!

Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x182c4efe0 __exceptionPreprocess
1  libobjc.A.dylib                0x1816b0538 objc_exception_throw
2  CoreFoundation                 0x182c5690c __CFAllocateObject
3  CoreFoundation                 0x182c40888 -[NSArray objectAtIndex:]
4  MintLive                       0x1003707dc ____shield_hook_auto_load_function_1_block_invoke (NSArrayObjectAtIndex.h:17)
5  MintLive                       0x100370fa8 ____shield_hook_auto_load_function_2_block_invoke (NSArrayObjectAtIndex.h:17)
6  CoreFoundation                 0x182ba798c CFStringCreateByCombiningStrings
7  CFNetwork                      0x183446d0c HTTPHeaderDict::copyStringValue(__CFAllocator const*, HTTPHeaderKeyMixedValue const&) const
8  CFNetwork                      0x18334c570 HTTPMessage::copyHeaderFieldValue(CFNetworkCanonicalStringConstant)
9  CFNetwork                      0x18338bda4 HTTPProtocol::_requestsAreCacheEquivalent(_CFURLRequest const*, _CFURLRequest const*, NSURLSession const*, void const*)
10 CFNetwork                      0x183323c34 +[_NSCFURLProtocol requestIsCacheEquivalent:toRequest:]
11 CFNetwork                      0x1832f9994 __CFURLCache::calloutForAsyncDiskCache(__CFString const*, _CFURLRequest const*, NSURLSession const*, void (_CFCachedURLResponse const*) block_pointer)
12 CFNetwork                      0x1832f5ae0 __CFURLCache::CopyResponseForRequestWithCompletionHandler(_CFURLRequest const*, bool, NSURLSession const*, void (_CFCachedURLResponse const*) block_pointer)
13 CFNetwork                      0x183462b18 CFXURLCache::getResponseForTask(NSURLSessionTask const*, unsigned char, void (_CFCachedURLResponse const*) block_pointer) const
14 CFNetwork                      0x1833e1718 URLConnectionLoader::_loaderEvent_StartLoad(NSURLSessionTask const*)
15 CFNetwork                      0x18332753c -[__NSCFURLLocalSessionConnection withLoaderOnQueue:]
16 CFNetwork                      0x183327b3c -[__NSCFURLLocalSessionConnection _tick_initialize]
17 CFNetwork                      0x1833270f0 __71-[__NSCFURLLocalSessionConnection initWithTask:delegate:delegateQueue:]_block_invoke
18 libdispatch.dylib              0x181b069e0 _dispatch_call_block_and_release
19 libdispatch.dylib              0x181b069a0 _dispatch_client_callout
20 libdispatch.dylib              0x181b14ad4 _dispatch_queue_serial_drain
21 libdispatch.dylib              0x181b0a2cc _dispatch_queue_invoke
22 libdispatch.dylib              0x181b14fa8 _dispatch_queue_override_invoke
23 libdispatch.dylib              0x181b16a50 _dispatch_root_queue_drain
24 libdispatch.dylib              0x181b167d0 _dispatch_worker_thread3
25 libsystem_pthread.dylib        0x181d0f100 _pthread_wqthread
26 libsystem_pthread.dylib        0x181d0ecac start_wqthread

**Comment by ValiantCat** [comment]
配置呢？

**Comment by faterman** [comment]
配置是指？

**Comment by ValiantCat** [comment]
2.2.0 已经发布
