### ISSUE TITLE
无法拦截UnrecognizedSelector

### ISSUE THREAD

**Issue by mistdon** [ValiantCat/XXShield#13]
在Demo/XXTimerViewController文件中，注册
```
[XXShieldSDK registerStabilityWithAbility:EXXShieldTypeUnrecognizedSelector];
```
在TouchesBegan... 方法中实现
```
NSArray *temp = [NSArray array];
[temp performSelector:@selector(integerValue)];
```
仍然会得到 **unrecognized selector sent to instance** 的crash。

Why？

**Comment by ValiantCat** [comment]
之前很多使用者建议不要hook 系统类  所以这里屏蔽到了系统类 只能hook开发者自己的类

**Comment by mistdon** [comment]
@ValiantCat **无法获取sectionData**

Podfile
```
platform :ios, '8.0'
use_frameworks!
target 'Test' do
   pod 'XXShield'
end
```
注册时机
```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    // Override point for customization after application launch.
    [XXShieldSDK registerStabilityWithAbility:EXXShieldTypeUnrecognizedSelector];
    return YES;
}
```
类加载
![2018-07-04 11 02 59](https://user-images.githubusercontent.com/11925085/42254583-df279666-7f79-11e8-9116-044dd85628bd.png)
结果：
```
void shield_hook_load_group(NSString *groupName) {
    uint32_t count = _dyld_image_count();
    for (uint32_t i = 0 ; i < count ; i ++) {
        const struct mach_header_* header = (void*)_dyld_get_image_header(i);
        NSString *string = [NSString stringWithFormat:@"__sh%@",groupName];
        unsigned long size = 0;
        uint8_t *data = getsectiondata(header, "__DATA", [string UTF8String],&size);
        if (data && size > 0) {
--->>>>  无法获取data，无法执行到这一步**
            void **pointers = (void**)data;
            uint32_t count = (uint32_t)(size / sizeof(void*));
            for (uint32_t i = 0 ; i < count ; i ++) {
                void(*pointer)() = pointers[i];
                pointer();
            }
            break;
        }
    }
}
```
Crash:
```
    SDModel *model = [SDModel new];
    [model performSelector:@selector(objectForKey:)];
```
请问是什么原因呢？

**Comment by shevakuilin** [comment]
@ValiantCat hi，如果我想在 XXShield 的基础上 hook 系统的类，应该怎么做呢

**Comment by shevakuilin** [comment]
@ValiantCat hi，如果我想在 XXShield 的基础上 hook 系统的类，应该怎么做呢

**Comment by ValiantCat** [comment]
一般不会出现的

**Comment by DracarysL** [comment]
我同样遇到了无法获取sectionData问题，请问怎么解决？

**Comment by jizhengzhu** [comment]
我也出现了这种情况：
void shield_hook_load_group(NSString *groupName) {
    uint32_t count = _dyld_image_count();
    for (uint32_t i = 0 ; i < count ; i ++) {
        const struct mach_header_* header = (void*)_dyld_get_image_header(i);
        NSString *string = [NSString stringWithFormat:@"__sh%@",groupName];
        unsigned long size = 0;
        uint8_t *data = getsectiondata(header, "__DATA", [string UTF8String],&size);
        if (data && size > 0) {
--->>>>  无法获取data，无法执行到这一步**
            void **pointers = (void**)data;
            uint32_t count = (uint32_t)(size / sizeof(void*));
            for (uint32_t i = 0 ; i < count ; i ++) {
                void(*pointer)() = pointers[i];
                pointer();
            }
            break;
        }
    }
}
