### ISSUE TITLE
这种情况的上下文是什么 / 1 如果是NSSNumber 和NSString没找到就是类型不对  切换下类型就好了

### ISSUE THREAD

**Issue by JunyiXie** [ValiantCat/XXShield#20]
// 1 如果是NSSNumber 和NSString没找到就是类型不对  切换下类型就好了
    if ([self isKindOfClass:[NSNumber class]] && [NSString instancesRespondToSelector:aSelector]) {
        NSNumber *number = (NSNumber *)self;
        NSString *str = [number stringValue];
        return str;
    } else if ([self isKindOfClass:[NSString class]] && [NSNumber instancesRespondToSelector:aSelector]) {
        NSString *str = (NSString *)self;
        NSNumberFormatter *formatter = [[NSNumberFormatter alloc] init];
        NSNumber *number = [formatter numberFromString:str];
        return number;
    }

**Comment by ValiantCat** [comment]
就是 NSNumber 其实也有stringValue NSString 也有  同名的stringvalue  没必要重新创建类型转发 这样性能较好
