### ISSUE TITLE
cocoapods1.5.3导入2.2.0运行报错

### ISSUE THREAD

**Issue by weixingdeng** [ValiantCat/XXShield#23]
#7 和这个一样，但是没解决
我使用CocoaPod 1.5.3版本，XXShield 2.2.0版本，直接运行还是会报错。
    导入libc++或者注释NSObject+DanglingPointer里面的static std::list<id> undellocedList可以运行，但是拦截不到任何崩溃。
    你的demo没有问题。麻烦看下

**Comment by ValiantCat** [comment]
我这里也没有复现啊 所以我一脸懵逼

**Comment by weixingdeng** [comment]
嗯 原因是我Podfile里面没有加use_frameworks!
