### ISSUE TITLE
源码问题

### ISSUE THREAD

**Issue by shangqianForFun** [ValiantCat/XXShield#27]
if ([self isKindOfClass:[NSNumber class]] && [NSString instancesRespondToSelector: aSelector]) {
        NSNumber * number = (NSNumber *)self;
        NSString * str = [number stringValue];
        return str;
    } else if ([self isKindOfClass:[NSString class]] && [NSNumber instancesRespondToSelector: aSelector]) {
        NSString * str = (NSString *)self;
        NSNumberFormatter * formatter = [[NSNumberFormatter alloc] init];
        NSNumber * number = [formatter numberFromString: str];
        return number;
    }
在消息转发的时候为什么加上NSString 和NSNumber 的判断直接拦击转发不行吗

**Comment by ValiantCat** [comment]
他们有同名的方法可以互相转换
