### ISSUE TITLE
项目实现第一个功能判断不正确,实现第二个项目会crash

### ISSUE THREAD

**Issue by Matthew1874** [ValiantCat/XXShield#3]
你好,本人小白一枚,了解到SDK的功能强大👍导入了项目,使用过程中遇到以下问题,如有本人使用错误望谅解:
Xcode9.1 iOS设备10.3.3
### 1.实现第一个功能Unrecoginzed Selector Crash 判断不正常,
我在某一个控制器中的viewWillAppear 写入以下代码 `UIButton *btn = [[UIButton alloc] init];
    [btn performSelector:@selector(some)];` 运行项目的时候 在这个方法`XXStaticHookClass(NSObject, ProtectFW, id, @selector(forwardingTargetForSelector:), (SEL)aSelector) { } `里 直接进入了这个判读然后return了 `if (strcmp(app_info.dli_fname, self_info.dli_fname)) {
        return XXHookOrgin(aSelector);
    }` 我注释了这个判断又可以实现了第一个功能
## 2.实现第二个功能KVO Crash 项目会crash
具体情况就是我用AFN 3.0进行请求  就会crash 附上日志
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x103c33e10 of class __NSCFLocalDataTask was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x174034240> (
<NSKeyValueObservance 0x174243510: Observer: 0x170095220, Key path: countOfBytesReceived, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x174243540>
<NSKeyValueObservance 0x174243840: Observer: 0x170095220, Key path: countOfBytesExpectedToReceive, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x174243870>
<NSKeyValueObservance 0x174243a50: Observer: 0x170095220, Key path: countOfBytesSent, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x174243a80>
<NSKeyValueObservance 0x174243c00: Observer: 0x170095220, Key path: countOfBytesExpectedToSend, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x174243c30>
谢谢

**Comment by ValiantCat** [comment]
关于第一个，通常认为hook系统的类是非常有安全隐患的。所以我这里过滤掉了系统类，如果你这个不是UIButton等系统类，而是自定义的类，就能正常防护了。
第二个的话有没有具体的例子什么的可以联系我
