### ISSUE TITLE
Xcode 11 cocoapods1.8.3 装完编译各种报错

### ISSUE THREAD

**Issue by summer87279149** [ValiantCat/XXShield#30]
ndefined symbols for architecture x86_64:
  "___cxa_allocate_exception", referenced from:
      std::__1::__throw_length_error(char const*) in libXXShield.a(NSObject+DanglingPointer.o)
  "operator delete(void*)", referenced from:
      std::__1::_DeallocateCaller::__do_call(void*) in libXXShield.a(NSObject+DanglingPointer.o)
  "vtable for std::length_error", referenced from:
      std::length_error::length_error(char const*) in libXXShield.a(NSObject+DanglingPointer.o)
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "std::length_error::~length_error()", referenced from:
      std::__1::__throw_length_error(char const*) in libXXShield.a(NSObject+DanglingPointer.o)
  "std::logic_error::logic_error(char const*)", referenced from:
      std::length_error::length_error(char const*) in libXXShield.a(NSObject+DanglingPointer.o)
  "___cxa_begin_catch", referenced from:
      ___clang_call_terminate in libXXShield.a(NSObject+DanglingPointer.o)
  "operator new(unsigned long)", referenced from:
      std::__1::__libcpp_allocate(unsigned long, unsigned long) in libXXShield.a(NSObject+DanglingPointer.o)
  "typeinfo for std::length_error", referenced from:
      std::__1::__throw_length_error(char const*) in libXXShield.a(NSObject+DanglingPointer.o)
  "___cxa_throw", referenced from:
      std::__1::__throw_length_error(char const*) in libXXShield.a(NSObject+DanglingPointer.o)
  "___cxa_free_exception", referenced from:
      std::__1::__throw_length_error(char const*) in libXXShield.a(NSObject+DanglingPointer.o)
  "std::terminate()", referenced from:
      ___clang_call_terminate in libXXShield.a(NSObject+DanglingPointer.o)
  "___gxx_personality_v0", referenced from:
      std::__1::list<objc_object*, std::__1::allocator<objc_object*> >::push_back(objc_object*&&) in libXXShield.a(NSObject+DanglingPointer.o)
      std::__1::__list_imp<objc_object*, std::__1::allocator<objc_object*> >::clear() in libXXShield.a(NSObject+DanglingPointer.o)
      std::__1::__list_imp<objc_object*, std::__1::allocator<objc_object*> >::__end_as_link() const in libXXShield.a(NSObject+DanglingPointer.o)
      std::__1::allocator<std::__1::__list_node<objc_object*, void*> >::deallocate(std::__1::__list_node<objc_object*, void*>*, unsigned long) in libXXShield.a(NSObject+DanglingPointer.o)
      std::__1::__list_imp<objc_object*, std::__1::allocator<objc_object*> >::__list_imp() in libXXShield.a(NSObject+DanglingPointer.o)
      std::__1::__throw_length_error(char const*) in libXXShield.a(NSObject+DanglingPointer.o)
      std::__1::unique_ptr<std::__1::__list_node<objc_object*, void*>, std::__1::__allocator_destructor<std::__1::allocator<std::__1::__list_node<objc_object*, void*> > > >::unique_ptr<true, void>(std::__1::__list_node<objc_object*, void*>*, std::__1::__dependent_type<std::__1::__unique_ptr_deleter_sfinae<std::__1::__allocator_destructor<std::__1::allocator<std::__1::__list_node<objc_object*, void*> > > >, true>::__good_rval_ref_type) in libXXShield.a(NSObject+DanglingPointer.o)
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by summer87279149** [comment]
ndefined symbols for architecture x86_64:
  "___cxa_allocate_exception", referenced from:
      std::__1::__throw_length_error(char const*) in libXXShield.a(NSObject+DanglingPointer.o)
  "operator delete(void*)", referenced from:
      std::__1::_DeallocateCaller::__do_call(void*) in libXXShield.a(NSObject+DanglingPointer.o)
  "vtable for std::length_error", referenced from:
      std::length_error::length_error(char const*) in libXXShield.a(NSObject+DanglingPointer.o)
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "std::length_error::~length_error()", referenced from:
      std::__1::__throw_length_error(char const*) in libXXShield.a(NSObject+DanglingPointer.o)
  "std::logic_error::logic_error(char const*)", referenced from:
      std::length_error::length_error(char const*) in libXXShield.a(NSObject+DanglingPointer.o)
  "___cxa_begin_catch", referenced from:
      ___clang_call_terminate in libXXShield.a(NSObject+DanglingPointer.o)
  "operator new(unsigned long)", referenced from:
      std::__1::__libcpp_allocate(unsigned long, unsigned long) in libXXShield.a(NSObject+DanglingPointer.o)
  "typeinfo for std::length_error", referenced from:
      std::__1::__throw_length_error(char const*) in libXXShield.a(NSObject+DanglingPointer.o)
  "___cxa_throw", referenced from:
      std::__1::__throw_length_error(char const*) in libXXShield.a(NSObject+DanglingPointer.o)
  "___cxa_free_exception", referenced from:
      std::__1::__throw_length_error(char const*) in libXXShield.a(NSObject+DanglingPointer.o)
  "std::terminate()", referenced from:
      ___clang_call_terminate in libXXShield.a(NSObject+DanglingPointer.o)
  "___gxx_personality_v0", referenced from:
      std::__1::list<objc_object*, std::__1::allocator<objc_object*> >::push_back(objc_object*&&) in libXXShield.a(NSObject+DanglingPointer.o)
      std::__1::__list_imp<objc_object*, std::__1::allocator<objc_object*> >::clear() in libXXShield.a(NSObject+DanglingPointer.o)
      std::__1::__list_imp<objc_object*, std::__1::allocator<objc_object*> >::__end_as_link() const in libXXShield.a(NSObject+DanglingPointer.o)
      std::__1::allocator<std::__1::__list_node<objc_object*, void*> >::deallocate(std::__1::__list_node<objc_object*, void*>*, unsigned long) in libXXShield.a(NSObject+DanglingPointer.o)
      std::__1::__list_imp<objc_object*, std::__1::allocator<objc_object*> >::__list_imp() in libXXShield.a(NSObject+DanglingPointer.o)
      std::__1::__throw_length_error(char const*) in libXXShield.a(NSObject+DanglingPointer.o)
      std::__1::unique_ptr<std::__1::__list_node<objc_object*, void*>, std::__1::__allocator_destructor<std::__1::allocator<std::__1::__list_node<objc_object*, void*> > > >::unique_ptr<true, void>(std::__1::__list_node<objc_object*, void*>*, std::__1::__dependent_type<std::__1::__unique_ptr_deleter_sfinae<std::__1::__allocator_destructor<std::__1::allocator<std::__1::__list_node<objc_object*, void*> > > >, true>::__good_rval_ref_type) in libXXShield.a(NSObject+DanglingPointer.o)
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by ValiantCat** [comment]
1.8.3属于beta版本把

**Comment by jingcaich** [comment]
同样的问题 ，应该是和 xcode 11.1 有些冲突

**Comment by ValiantCat** [comment]
please use XXShield  2.3.0 
@summer87279149  @jingcaich
