### ISSUE TITLE
 Unrecoginzed Selector Crash无效

### ISSUE THREAD

**Issue by jizhengzhu** [ValiantCat/XXShield#32]
iPhone7设备，iOS12.2系统版本，试了好几个项目，包括新建test项目，以及github上下载的这个项目，运行时执行[self performSelector:@selector(testAction)];但未实现testAction方法，这样做仍然会崩溃，
```ObjectiveC
void shield_hook_load_group(NSString *groupName) {
    uint32_t count = _dyld_image_count();
    for (uint32_t i = 0 ; i < count ; i ++) {
        const struct mach_header_* header = (void*)_dyld_get_image_header(i);
        NSString *string = [NSString stringWithFormat:@"__sh%@",groupName];
        unsigned long size = 0;
        uint8_t *data = getsectiondata(header, "__DATA", [string UTF8String],&size);
// 打断点运行到这里时，data为NULL，这样是不是相当于啥都没做，崩溃也就无法防护，但是不知道为啥这里data会为NULL，查了很多资料感觉都没搞清楚，希望能帮我解答一下；
        if (data && size > 0) {
            void **pointers = (void**)data;
            uint32_t count = (uint32_t)(size / sizeof(void*));
            for (uint32_t i = 0 ; i < count ; i ++) {
                void(*pointer)() = pointers[i];
                pointer();
            }
            break;
        }
    }
}
```

**Comment by ValiantCat** [comment]
你们难道是动态库接入

**Comment by jinghang-gaohongxu** [comment]
void shield_hook_load_group(NSString *groupName) {
    uint32_t count = _dyld_image_count();
    for (uint32_t i = 0 ; i < count ; i ++) {
        const struct mach_header_* header = (void*)_dyld_get_image_header(i);
        NSString *string = [NSString stringWithFormat:@"__sh%@",groupName];
        unsigned long size = 0;
        uint8_t *data = getsectiondata(header, "__DATA", [string UTF8String],&size);
        if (data && size > 0) {
            void **pointers = (void**)data;
            uint32_t count = (uint32_t)(size / sizeof(void*));
            for (uint32_t i = 0 ; i < count ; i ++) {
                void(*pointer)() = pointers[i];
                pointer();
            }
            break;
        }
    }
}

你好、这个方法我这里为啥只走了kvo和nstimer的防护方法、其他的data都为空。是什么原因呢

**Comment by ValiantCat** [comment]
使用Mach-O View 看下数据是否写入成功

**Comment by langzuxiaozi** [comment]
我也遇到了。 用Mach-O View 看，在 Section64(__DATA, 只有 __shProtectKVO 和 __shProtectTimer 两个

**Comment by langzuxiaozi** [comment]
那些在Section64中没有的，我在文件随便创建个类，就有了。这个是不是需要xcode配置点啥？

**Comment by ValiantCat** [comment]
@langzuxiaozi @jizhengzhu @jinghang-gaohongxu   ，因为没有人调用，有可能在链接阶段直接strp了
