### ISSUE TITLE
空可变数组，在0处插入数据的bug

### ISSUE THREAD

**Issue by zhiliang729** [ValiantCat/XXShield#5]
NSMutableArray *array = [NSMutableArray array];     array[0] = @"hello";

**Comment by zhiliang729** [comment]
XXStaticHookPrivateClass(__NSArrayM, NSMutableArray *, ProtectCont, void, @selector(setObject:atIndexedSubscript:), (id) obj, (NSUInteger) idx) {
    if (obj) {
        if (idx >= self.count) {
            NSString *reason = [NSString stringWithFormat:@"target is %@ method is %@,reason : index %@ out of count %@ of marray ",
                                [self class], XXSEL2Str(@selector(setObject:atIndexedSubscript:)) ,@(idx), @(self.count)];
            [XXRecord recordFatalWithReason:reason errorType:(EXXShieldTypeContainer)];
        } else {
            XXHookOrgin(obj, idx);
        }
    } else {
        NSString *reason = [NSString stringWithFormat:@"target is %@ method is %@, reason : object appear nil obj is %@",
                            [self class], XXSEL2Str(@selector(setObject:atIndexedSubscript:)), obj];
        [XXRecord recordFatalWithReason:reason errorType:(EXXShieldTypeContainer)];
    }
}
XXStaticHookEnd


if (idx >= self.count) { idex 0， count 0

**Comment by zhiliang729** [comment]
if (idx >= self.count) { 是不是应该替换为 if (idx > self.count) {

**Comment by zhiliang729** [comment]
NSMutableArray *array = [NSMutableArray arrayWithArray:@[@"0"]];
    array[1] = @"hello";
    NSLog(@"array %@", array.description);
    
//    2018-01-06 15:40:21.914107+0800 test[5812:679615] array (
//                                                             0,
//                                                             hello
//                                                             )
    
    NSMutableArray *array1 = [NSMutableArray arrayWithArray:@[@"0"]];
    array1[0] = @"hello";
    NSLog(@"array1 %@", array1.description);
//    2018-01-06 15:40:41.522054+0800 test[5815:680020] array (
//                                                             hello
//                                                             )

**Comment by zhiliang729** [comment]
NSMutableArray *array2 = [NSMutableArray array];
    array2[0] = @"hello";
    NSLog(@"array2 %@", array2.description);
//    2018-01-06 15:44:27.176926+0800 test[5835:682244] array2 (
//                                                              hello
//                                                              )

**Comment by ValiantCat** [comment]
已修复 2.1.1 版本
