### ISSUE TITLE
pod install 之后打开工程就直接报错了

### ISSUE THREAD

**Issue by whatsbug** [ValiantCat/XXShield#7]
![2018-03-19 04 36 50 pm](https://user-images.githubusercontent.com/7418617/37585368-dd42efb0-2b93-11e8-9780-e44764619514.png)

**Comment by whatsbug** [comment]
把NSObject+DanglingPointer.mm文件下的这一句代码(及其相关代码)“static std::list<id> undellocedList”注释掉就可以运行了。如此看来和c++代码有关，具体原因是什么还望告知

**Comment by ValiantCat** [comment]
需要 libC++

**Comment by whatsbug** [comment]
之前试过link相关的c++库，虽然不报错了，但这个库根本没起作用(我已正确初始化的情况下)，但在你本身的demo下测试是会起作用的。推测是环境配置问题，按理说pod进来的库，相关配置你不是应该配置好了的吗

**Comment by ValiantCat** [comment]
pod 升级了 1.5.0 吧  可能是环境有冲突

**Comment by ValiantCat** [comment]
pod 1.5.3  XXShield 2.2.0已经发布
