### ISSUE TITLE
XXHookOrgin崩溃

### ISSUE THREAD

**Issue by ryanwangh** [ValiantCat/XXShield#9]
hook方法：
`XXStaticHookPrivateClass(__NSCFConstantString, NSString *, ProtectCont, NSString *, @selector(rangeOfString:options:range:), (NSString *)searchString, (NSStringCompareOptions)mask, (NSRange)rangeOfReceiverToSearch) {
    if (searchString == nil) {
        NSString *reason = [NSString stringWithFormat:@"[%@ %@]: nil argument",
                            [self class], XXSEL2Str(@selector(rangeOfString:options:range:))];
        [XXRecord recordFatalWithReason:reason errorType:EXXShieldTypeContainer];
        return nil;
    } else if (rangeOfReceiverToSearch.location > self.length ||
               rangeOfReceiverToSearch.length > self.length ||
               (rangeOfReceiverToSearch.location + rangeOfReceiverToSearch.length) > self.length {
//               searchString.length > rangeOfReceiverToSearch.length) {
        NSString *reason = [NSString stringWithFormat:@"[%@ %@]: Range {%@, %@} out of bounds; string length %@",
                            [self class], XXSEL2Str(@selector(rangeOfString:options:range:)), @(rangeOfReceiverToSearch.location), @(rangeOfReceiverToSearch.length), @(self.length)];
        [XXRecord recordFatalWithReason:reason errorType:EXXShieldTypeContainer];
        return nil;
    }
    return XXHookOrgin(searchString, mask, rangeOfReceiverToSearch);//这一行崩溃
}
XXStaticHookEnd`

测试崩溃的代码：
`    NSString *string = @"1213";
    NSRange ranage = [string rangeOfString:@"12" options:1 range:NSMakeRange(0, 0)];`

然后XXHookOrgin就崩溃了，如果去掉这个hook方法，系统的方法本身并不会崩溃。没有看出来XXHookOrgin为什么会崩溃

**Comment by ValiantCat** [comment]
这个方法并不属于此SDK， 如需要添加请 提PR。

**Comment by ValiantCat** [comment]
如果需要扩充 你的hook方法 返回值不对 将NSString修改为NSRange
如下
XXStaticHookPrivateClass(__NSCFConstantString, NSString *, ProtectCont, ** #NSRange,** @selector(rangeOfString:options:range:), (NSString *)searchString, (NSStringCompareOptions)mask, (NSRange)rangeOfReceiverToSearch)

**Comment by ryanwangh** [comment]
多谢，已经好了
